
/* Generated by the NeXT Interface Builder */

#import <appkit/appkit.h>
#import <objc/Object.h>

@interface Controller : Object
{
    id	openReq;	// OpenPanel for open requests 
    id	saveReq;	// SavePanel for save-in requests
    id	fontReq;	// FontPanel for font requests
    id  archiver;
    id  errorText;	// TextField in error panel
}

- showError:(char *)errorMessage;
- setOpenReq:anObject;
- setSaveReq:anObject;
- setFontReq:anObject;
- setArchiver:anObject;
- setErrorText:anObject;
- newTextView:sender;
- openRequest:sender;
- printRequest:sender;
- saveRequest:sender;
- saveWindow:win inFile:(char *)name inDir:(char *)dirName;
- xstartup:sender;
- xfollowlink:sender;
- opendoc:(tumbler *)variabledocvpositionp :(int)start;
-terminate:sender;
@end
